version: '3.9'

services:

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: kiarashshahedi
      POSTGRES_PASSWORD: KiarashShahedi
      POSTGRES_DB: my_website_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: backend_db


  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
     - SECRET_KEY=test
     - DEBUG=True
    depends_on:
      - db
     
volumes:
  postgres_data:

