# Generated by Django 4.2.16 on 2024-09-04 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('accounts', '0001_initial'),
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_profile',
            name='buy_history',
            field=models.ManyToManyField(blank=True, to='orders.order'),
        ),
        migrations.AddField(
            model_name='buyer_profile',
            name='cart_history',
            field=models.ManyToManyField(blank=True, to='cart.cart'),
        ),
        migrations.AddField(
            model_name='buyer_profile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
        migrations.AddField(
            model_name='buyer_profile',
            name='seen_products',
            field=models.ManyToManyField(blank=True, to='products.products'),
        ),
        migrations.AddField(
            model_name='buyer_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
