# Generated by Django 4.2.15 on 2024-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
