# Generated by Django 4.2.15 on 2024-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custom_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
