# Generated by Django 4.2.15 on 2024-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_custom_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='meli_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
