# Generated by Django 4.2.15 on 2024-09-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_custom_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='meli_code',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Seller_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=10, unique=True)),
                ('meli_code', models.CharField(max_length=10, unique=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_sales', models.PositiveIntegerField(default=0)),
                ('preferred_shipping_method', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_support_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_routing_number', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('buy_status', models.BooleanField(default=False)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=10, unique=True)),
                ('meli_code', models.CharField(max_length=10, unique=True)),
                ('product_points', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
