# Generated by Django 4.2.15 on 2024-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_custom_user_address_remove_custom_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_profile',
            name='meli_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='buyer_profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
