# Generated by Django 4.2.15 on 2024-09-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_buyer_profile_meli_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_profile',
            name='meli_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
