# Generated by Django 4.2.15 on 2024-09-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_buyer_profile_meli_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
