# Generated by Django 4.2.15 on 2024-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_buyer_profile_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
